POST http://localhost:8080/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzIzODUwMTkwLCJ1c2VySWQiOjJ9.6hredqlc5W45-Ek51QBR8YUrQ2du4gwlM_mfNZBCPGM

{
  "name": "Test Event 2.2",
  "description": "Event 2.2",
  "location": "Test Location",
  "dateTime": "2021-12-31T23:59:59Z"
}